/*
 * PingOne Platform API
 *
 * A bare-bones collection for the PingOne API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
)

// Linger please
var (
	_ _context.Context
)

// ManagementAPIsApplicationsApplicationRoleAssignmentsApiService ManagementAPIsApplicationsApplicationRoleAssignmentsApi service
type ManagementAPIsApplicationsApplicationRoleAssignmentsApiService service

type ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService
	envID string
	appID string
	authorization *string
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetRequest {
	r.authorization = &authorization
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGet READ Application Role Assignments
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetRequest
 */
func (a *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService) V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGet(ctx _context.Context, envID string, appID string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService) V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGetRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationRoleAssignmentsApiService.V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsGet")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/roleAssignments"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService
	envID string
	appID string
	contentType *string
	authorization *string
	body *map[string]interface{}
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest) ContentType(contentType string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest {
	r.contentType = &contentType
	return r
}
func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest {
	r.authorization = &authorization
	return r
}
func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest) Body(body map[string]interface{}) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest {
	r.body = &body
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPost CREATE Application Role Assignments
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest
 */
func (a *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService) V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPost(ctx _context.Context, envID string, appID string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService) V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPostRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationRoleAssignmentsApiService.V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsPost")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/roleAssignments"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.contentType != nil {
		localVarHeaderParams["Content-Type"] = parameterToString(*r.contentType, "")
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService
	envID string
	appID string
	roleAssignmentID string
	authorization *string
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteRequest {
	r.authorization = &authorization
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDelete DELETE Application Role Assignment
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @param roleAssignmentID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteRequest
 */
func (a *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService) V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDelete(ctx _context.Context, envID string, appID string, roleAssignmentID string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
		roleAssignmentID: roleAssignmentID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService) V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDeleteRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodDelete
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationRoleAssignmentsApiService.V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDDelete")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/roleAssignments/{roleAssignmentID}"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"roleAssignmentID"+"}", _neturl.PathEscape(parameterToString(r.roleAssignmentID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService
	envID string
	appID string
	roleAssignmentID string
	authorization *string
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetRequest {
	r.authorization = &authorization
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGet READ One Application Role Assignment
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @param roleAssignmentID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetRequest
 */
func (a *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService) V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGet(ctx _context.Context, envID string, appID string, roleAssignmentID string) ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
		roleAssignmentID: roleAssignmentID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationRoleAssignmentsApiService) V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGetRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationRoleAssignmentsApiService.V1EnvironmentsEnvIDApplicationsAppIDRoleAssignmentsRoleAssignmentIDGet")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/roleAssignments/{roleAssignmentID}"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"roleAssignmentID"+"}", _neturl.PathEscape(parameterToString(r.roleAssignmentID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
