/*
 * PingOne Platform API
 *
 * A bare-bones collection for the PingOne API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
)

// Linger please
var (
	_ _context.Context
)

// ManagementAPIsApplicationsApplicationAttributeMappingApiService ManagementAPIsApplicationsApplicationAttributeMappingApi service
type ManagementAPIsApplicationsApplicationAttributeMappingApiService service

type ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesGetRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationAttributeMappingApiService
	envID string
	appID string
	authorization *string
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesGetRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesGetRequest {
	r.authorization = &authorization
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesGetRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesGetExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDAttributesGet READ All Application Attribute Mappings
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesGetRequest
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesGet(ctx _context.Context, envID string, appID string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesGetRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesGetRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesGetExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesGetRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationAttributeMappingApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesGet")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/attributes"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationAttributeMappingApiService
	envID string
	appID string
	contentType *string
	authorization *string
	body *map[string]interface{}
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest) ContentType(contentType string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest {
	r.contentType = &contentType
	return r
}
func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest {
	r.authorization = &authorization
	return r
}
func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest) Body(body map[string]interface{}) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest {
	r.body = &body
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesPostExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDAttributesPost CREATE Application Attribute Mapping
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesPost(ctx _context.Context, envID string, appID string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesPostExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesPostRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationAttributeMappingApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesPost")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/attributes"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.contentType != nil {
		localVarHeaderParams["Content-Type"] = parameterToString(*r.contentType, "")
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationAttributeMappingApiService
	envID string
	appID string
	samlAttrID string
	authorization *string
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteRequest {
	r.authorization = &authorization
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDelete DELETE Application Attribute Mapping
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @param samlAttrID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteRequest
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDelete(ctx _context.Context, envID string, appID string, samlAttrID string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
		samlAttrID: samlAttrID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDeleteRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodDelete
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationAttributeMappingApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDDelete")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/attributes/{samlAttrID}"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"samlAttrID"+"}", _neturl.PathEscape(parameterToString(r.samlAttrID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationAttributeMappingApiService
	envID string
	appID string
	samlAttrID string
	authorization *string
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetRequest {
	r.authorization = &authorization
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGet READ One Application Attribute Mapping
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @param samlAttrID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetRequest
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGet(ctx _context.Context, envID string, appID string, samlAttrID string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
		samlAttrID: samlAttrID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGetRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationAttributeMappingApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDGet")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/attributes/{samlAttrID}"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"samlAttrID"+"}", _neturl.PathEscape(parameterToString(r.samlAttrID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest struct {
	ctx _context.Context
	ApiService *ManagementAPIsApplicationsApplicationAttributeMappingApiService
	envID string
	appID string
	samlAttrID string
	contentType *string
	authorization *string
	body *map[string]interface{}
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest) ContentType(contentType string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest {
	r.contentType = &contentType
	return r
}
func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest) Authorization(authorization string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest {
	r.authorization = &authorization
	return r
}
func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest) Body(body map[string]interface{}) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest {
	r.body = &body
	return r
}

func (r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutExecute(r)
}

/*
 * V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPut UPDATE Application Attribute Mapping
 * By design, PingOne requests solely comprise this collection. For complete documentation, direct a browser to <a href='https://apidocs.pingidentity.com/pingone/platform/v1/api/'>apidocs.pingidentity.com</a>.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param envID
 * @param appID
 * @param samlAttrID
 * @return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPut(ctx _context.Context, envID string, appID string, samlAttrID string) ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest {
	return ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest{
		ApiService: a,
		ctx: ctx,
		envID: envID,
		appID: appID,
		samlAttrID: samlAttrID,
	}
}

/*
 * Execute executes the request
 */
func (a *ManagementAPIsApplicationsApplicationAttributeMappingApiService) V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutExecute(r ApiV1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPutRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPut
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ManagementAPIsApplicationsApplicationAttributeMappingApiService.V1EnvironmentsEnvIDApplicationsAppIDAttributesSamlAttrIDPut")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/environments/{envID}/applications/{appID}/attributes/{samlAttrID}"
	localVarPath = strings.Replace(localVarPath, "{"+"envID"+"}", _neturl.PathEscape(parameterToString(r.envID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"appID"+"}", _neturl.PathEscape(parameterToString(r.appID, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"samlAttrID"+"}", _neturl.PathEscape(parameterToString(r.samlAttrID, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.contentType != nil {
		localVarHeaderParams["Content-Type"] = parameterToString(*r.contentType, "")
	}
	if r.authorization != nil {
		localVarHeaderParams["Authorization"] = parameterToString(*r.authorization, "")
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
